name: Flutter CI/CD

on:
  push:
    tags:
      - 'build*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx4096m"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug --flavor premium lib/main.dart

      - name: Save Firebase service account to file
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-service-account.json

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase using service account
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        run: firebase projects:list

      - name: Read release notes
        id: release_notes
        run: cat release_notes.txt

      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          firebase appdistribution:distribute build/app/outputs/apk/premium/debug/app-premium-debug.apk \
            --app $FIREBASE_APP_ID \
            --release-notes "$(cat release_notes.txt)" \
            --groups "tested"

      - name: Remove credentials file
        if: always()
        run: rm firebase-service-account.json
