name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Temurin JDK, the recommended JDK for Android development

      # Setup Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      # Run flutter pub get to install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the APK
      - name: Build APK
        run: flutter build apk --debug --flavor premium lib/main.dart

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/apk/premium/debug/app-premium-debug.apk

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > ${HOME}/firebase-service-account.json
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --token $FIREBASE_TOKEN \
            --groups "tested"